saltminion 3006.5 - Corrected url/64_py3 and checksum/64_py3
barkingfoodog/ChocolateySaltMinion pull request #12
Opened 2024-05-19 23:15 UTC by LeaDevelop

Path to saltminion .exe on official saltstack repository has changed through time and chocolatey packages will result in failure to install. It makes sense to keep history version for 3006.x up to date as it is a LTS version.
https://docs.saltproject.io/salt/install-guide/en/latest/topics/salt-version-support-lifecycle.html#version-support-lifecycle

-  I created directory and pulled chocolateyuninstall.ps1 script, it is untouched.
-  chocolateyinstall.ps1 script got url corrections for both executables including the checksums
-  saltminion.nuspc got url corrections for documentation and pointed to up to date official logo

2024-05-20 18:01 UTC, twangboy requested changes

2024-05-20 18:01 UTC, twangboy commented on 3006-5/saltminion.nuspec
> +    <authors>SaltStack</authors>
Salt Project

2024-05-20 18:01 UTC, twangboy commented on 3006-5/saltminion.nuspec
> +    <projectUrl>https://www.saltstack.com/</projectUrl>
www.saltproject.io

2024-05-20 18:01 UTC, twangboy commented on 3006-5/saltminion.nuspec
> +    <docsUrl>https://docs.saltstack.com/en/3006/contents.html</docsUrl>
https://docs.saltproject.io/en/3006/contents.html

2024-05-21 15:39 UTC, twangboy approved these changes

2024-06-17 03:01 UTC, barkingfoodog commented
Hi, thank you for the update! Would you please move the `tools/` directory one level higher and eliminate the `saltminion/` directory? This will allow the relative path in `saltminion.nuspec` to locate the files under `tools/`.

2024-06-18 18:35 UTC, LeaDevelop commented
@barkingfoodog PR was aligned with master branch and suggested improvements done, ready for review

2024-06-20 14:33 UTC, merged